install: |-
  sudo apt-get install bsdmainutils
  sudo gem install pdd
  sudo gem install est
  sudo apt-get install ruby
  sudo apt-get install maven
docker:
  image: mostalive/ubuntu-14.04-oracle-jdk8
architect:
- yegor256
- karato
assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  id_rsa: yegor256/home#assets/heroku-key
  settings.xml: yegor256/home#assets/nerodesk/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
  s3cfg: yegor256/home#assets/s3cfg
merge:
  script: |-
    mvn help:system clean install -Pqulice,cobertura -Pnerodesk --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
  commanders:
  - alevohin
  - caarlos0
  - carlosmiranda
  - darkled
  - krzyk
  - longtimeago
  - maurezen
  - yegor256
deploy:
  script: |-
    mvn clean package -Pnerodesk -Pqulice,cobertura --errors --settings ../settings.xml --batch-mode
    mvn clean
    pdd --source=$(pwd) --verbose --file=nerodesk.xml
    s3cmd --no-progress put nerodesk.xml --config=../s3cfg s3://pdd.teamed.io/nerodesk.xml
    est --dir=$(pwd)/est --verbose --file=nerodesk.xml --format=xml
    s3cmd --no-progress put nerodesk.xml --config=../s3cfg s3://est.teamed.io/nerodesk.xml
  commanders:
  - ggajos
  - yegor256
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    cp ../settings.xml settings.xml
    mvn clean package -Pqulice -Pnerodesk --errors --batch-mode
    git remote add heroku git@heroku.com:nerodesk.git
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    build=$(git rev-parse --short HEAD)
    sed -i "s/BUILD/${build}/g" src/main/resources/META-INF/MANIFEST.MF
    sed -i "s/BUILD/${build}/g" src/main/resources/log4j.properties
    git add src/main/resources/META-INF/MANIFEST.MF
    git add src/main/resources/log4j.properties
    git commit -m 'build number set'
    git add settings.xml
    git commit -m 'settings.xml'
    git fetch --unshallow
    git push -f heroku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    curl -f --connect-timeout 30 --retry 8 --retry-delay 60 http://beta.nerodesk.com
    mvn clean site-deploy -Psite --errors --settings ../settings.xml --batch-mode
  commanders:
  - ggajos
  - yegor256